runtime: nodejs20 

instance_class: F2

env_variables:
  BUCKET_NAME: "dicodingprofile"

handlers:
- url: /index.html
  static_dir: index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto